
POST http://localhost:8080/usuarios HTTP/1.1
content-type: application/json
token:



{
    "nome": "Admin First",
    "perfil": "ADMINISTRADOR",
    "username": "admin1@teste.com",
    "senha": "growdev1234",
    "nomeEmpresa": "Gupy",
}

# # RECRUTADOR
# {
#     "name": "Recrutador 1",
#     "username": "recrutador@growdev.com.br",
#     "password": "123456",
#     "profile": "RECRUITER",
#     "company": "Growdev"
# }